[package]
name = "threadmill"
version = "0.1.0"
authors = ["post-rex <post-rex@pm.me>"]
edition = "2018"

[dependencies]
num_cpus = "1.13"
flume = "0.9"
until = "0.1"

[dev-dependencies]
rand = "0.7.3"