[package]
name = "threadmill"
version = "0.1.0"
authors = ["post-rex <post-rex@pm.me>"]
edition = "2018"

[dependencies]
num_cpus = "1.13"
flume = "0.9"
parking_lot = "0.11"
futures-task = "0.3"
log = "0.4"
rand = "0.7"

[dev-dependencies]
env_logger = "0.8.2"
